In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # for data visualization purposes
import seaborn as sns # for statistical data visualization
%matplotlib inline

In [23]:
from sklearn.datasets import load_digits
dataset = load_digits()
df= pd.DataFrame(dataset.data, columns=dataset.feature_names)
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

In [24]:
X=df
Y=dataset.target

In [4]:
df.shape

(2000, 21)

In [25]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
x_scaled = scaler.fit_transform(X)

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [27]:
X_train.isnull().sum()

pixel_0_0    0
pixel_0_1    0
pixel_0_2    0
pixel_0_3    0
pixel_0_4    0
            ..
pixel_7_3    0
pixel_7_4    0
pixel_7_5    0
pixel_7_6    0
pixel_7_7    0
Length: 64, dtype: int64

In [28]:
X_train.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
372,0.0,3.0,13.0,16.0,9.0,0.0,0.0,0.0,0.0,10.0,...,9.0,1.0,0.0,2.0,16.0,16.0,14.0,12.0,9.0,1.0
1443,0.0,0.0,1.0,14.0,13.0,4.0,0.0,0.0,0.0,3.0,...,6.0,0.0,0.0,0.0,0.0,9.0,14.0,13.0,1.0,0.0
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
211,0.0,0.0,8.0,16.0,13.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,12.0,9.0,0.0,0.0,0.0,0.0
632,0.0,0.0,1.0,13.0,7.0,0.0,0.0,0.0,0.0,1.0,...,4.0,2.0,0.0,0.0,1.0,15.0,16.0,15.0,13.0,15.0

In [51]:
from sklearn.neural_network import MLPClassifier
back_prop = MLPClassifier(activation='tanh',solver='sgd',hidden_layer_sizes=(80,100),max_iter=1000,random_state=1)

In [52]:
back_prop.fit(X_train,Y_train)

MLPClassifier(activation='tanh', hidden_layer_sizes=(80, 100), max_iter=1000,
              random_state=1, solver='sgd')

In [53]:
Y_pred = back_prop.predict(X_test)

In [54]:

from sklearn.metrics import confusion_matrix
  
cm = confusion_matrix(Y_test, Y_pred)
cm

array([[37,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 42,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0, 44,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 36,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 46,  0,  0,  0,  2],
       [ 0,  1,  0,  0,  0,  0, 51,  0,  0,  0],
       [ 0,  0,  0,  0,  2,  0,  0, 46,  0,  0],
       [ 0,  0,  1,  0,  0,  1,  1,  1, 41,  3],
       [ 0,  0,  0,  0,  0,  1,  0,  1,  0, 45]])

In [55]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred)*100,"%")

Accuracy: 96.0 %

In [50]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.98      0.98      0.98        43
           2       0.98      1.00      0.99        44
           3       1.00      0.93      0.97        45
           4       0.95      0.95      0.95        38
           5       0.94      0.96      0.95        48
           6       0.98      0.98      0.98        52
           7       0.92      0.96      0.94        48
           8       0.95      0.88      0.91        48
           9       0.90      0.96      0.93        47

    accuracy                           0.96       450
   macro avg       0.96      0.96      0.96       450
weighted avg       0.96      0.96      0.96       450