In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df = pd.read_csv("Pokemon.csv")

In [13]:
df.head()

,Name,Type,Strength,HP,Attack,Defense,Legendary
0,Thundurus Incarnate Forme,Electric,Medium,79,115,70,True
1,Mega Garchomp,Dragon,Strong,108,170,115,False
2,Rayquaza,Dragon,Strong,105,150,90,True
3,Ekans,Poison,Low,35,60,44,False
4,Reshiram,Dragon,Strong,100,120,100,True

In [14]:
df["Strength"].unique()

array(['Medium', 'Strong', 'Low'], dtype=object)

In [15]:
strength = ['Strong','Medium','Low']

In [16]:
enc = OrdinalEncoder(categories=[strength])

In [17]:
enc.fit_transform(df[["Strength"]])

array([[1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [1.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.]])

In [18]:
df[["Strength"]]=enc.fit_transform(df[["Strength"]])

In [19]:
df.head()

,Name,Type,Strength,HP,Attack,Defense,Legendary
0,Thundurus Incarnate Forme,Electric,1.0,79,115,70,True
1,Mega Garchomp,Dragon,0.0,108,170,115,False
2,Rayquaza,Dragon,0.0,105,150,90,True
3,Ekans,Poison,2.0,35,60,44,False
4,Reshiram,Dragon,0.0,100,120,100,True